// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEt9AocDPQ0ziD7kWx5zneRVmRHTcRHBg',
    appId: '1:452022753540:web:3f8b6c73cda8dc85d8d851',
    messagingSenderId: '452022753540',
    projectId: 'civitante',
    authDomain: 'civitante.firebaseapp.com',
    storageBucket: 'civitante.firebasestorage.app',
    measurementId: 'G-89ZXJGXJ2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa__zEouUu4yUGV7U2Tv2MmCjKvJJD2Fg',
    appId: '1:452022753540:android:668671f994bf9f7dd8d851',
    messagingSenderId: '452022753540',
    projectId: 'civitante',
    storageBucket: 'civitante.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYIVbEOR9bu_ScqDXrwxq816WL3oHrZQ',
    appId: '1:452022753540:ios:5320baf0eed5fb9ad8d851',
    messagingSenderId: '452022753540',
    projectId: 'civitante',
    storageBucket: 'civitante.firebasestorage.app',
    androidClientId: '452022753540-4fplhmji9fhpv79rf79s1tjpihq1hrp4.apps.googleusercontent.com',
    iosClientId: '452022753540-ue1iafpc78qefcnof086jkfb4nok3111.apps.googleusercontent.com',
    iosBundleId: 'com.personalaiapp.personalAiLifeAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkYIVbEOR9bu_ScqDXrwxq816WL3oHrZQ',
    appId: '1:452022753540:ios:5320baf0eed5fb9ad8d851',
    messagingSenderId: '452022753540',
    projectId: 'civitante',
    storageBucket: 'civitante.firebasestorage.app',
    androidClientId: '452022753540-4fplhmji9fhpv79rf79s1tjpihq1hrp4.apps.googleusercontent.com',
    iosClientId: '452022753540-ue1iafpc78qefcnof086jkfb4nok3111.apps.googleusercontent.com',
    iosBundleId: 'com.personalaiapp.personalAiLifeAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEt9AocDPQ0ziD7kWx5zneRVmRHTcRHBg',
    appId: '1:452022753540:web:ea7105ee57bab9b5d8d851',
    messagingSenderId: '452022753540',
    projectId: 'civitante',
    authDomain: 'civitante.firebaseapp.com',
    storageBucket: 'civitante.firebasestorage.app',
    measurementId: 'G-Q7SSZ5PZZ9',
  );
}
